parameters:
#    pidev_user.example.class: Pidev\UserBundle\Example

services:
#    pidev_user.example:
#        class: %pidev_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
