parameters:
#    pidevback.example.class: Pidev\backBundle\Example

services:
#    pidevback.example:
#        class: %pidevback.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
