parameters:
#    pidev_map.example.class: Pidev\MapBundle\Example

services:
#    pidev_map.example:
#        class: %pidev_map.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
