Administrateur:
    type: entity
    table: administrateur
    fields:
        idAdmin:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_admin
            generator:
                strategy: IDENTITY
        login:
            type: string
            length: 30
            fixed: false
            nullable: false
        motPasse:
            type: string
            length: 30
            fixed: false
            nullable: false
            column: mot_passe
    lifecycleCallbacks: {  }
