Categorie:
    type: entity
    table: categorie
    fields:
        idcategorie:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: idCategorie
            generator:
                strategy: IDENTITY
        nomcategorie:
            type: string
            length: 20
            fixed: false
            nullable: false
            column: nomCategorie
    lifecycleCallbacks: {  }
