Disponibilite:
    type: entity
    table: disponibilite
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        jour:
            type: string
            length: 20
            fixed: false
            nullable: false
        horaire:
            type: string
            length: 20
            fixed: false
            nullable: false
        idBabysitter:
            type: integer
            unsigned: false
            nullable: true
            column: id_babysitter
    lifecycleCallbacks: {  }
