Service:
    type: entity
    table: service
    fields:
        idservice:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: idService
            generator:
                strategy: IDENTITY
        typeservice:
            type: string
            length: 1000
            fixed: false
            nullable: true
            column: typeService
        description:
            type: string
            length: 2000
            fixed: false
            nullable: false
        idcategorie:
            type: integer
            unsigned: false
            nullable: true
            column: idCategorie
    lifecycleCallbacks: {  }
