Garderie:
    type: entity
    table: garderie
    fields:
        idGarderie:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_garderie
            generator:
                strategy: IDENTITY
        nomGarderie:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: nom_garderie
        villeGarderie:
            type: string
            length: 20
            fixed: false
            nullable: false
            column: ville_garderie
        adresseGarderie:
            type: text
            nullable: false
            column: adresse_garderie
        numTel:
            type: integer
            unsigned: false
            nullable: false
            column: 'num Tel'
        capaciteGarderie:
            type: integer
            unsigned: false
            nullable: false
            column: capacite_garderie
        descriptionGarderie:
            type: text
            nullable: false
            column: description_garderie
        contactGarderie:
            type: text
            nullable: false
            column: contact_garderie
        dateAjoutGarderie:
            type: date
            nullable: false
            column: date_ajout_garderie
    lifecycleCallbacks: {  }
