parameters:
#    pidev_front.example.class: Pidev\FrontBundle\Example

services:
#    pidev_front.example:
#        class: %pidev_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
